<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <AssemblyName>Tipsy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\net.queuepacked.Assembly.CPU\net.queuepacked.Assembly.CPU.csproj" />
  </ItemGroup>

</Project>
